### imports

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# Part 1: Data exploration with pandas

#### Load a dataset

In [134]:
# 1
df = pd.read_csv(r"c:\Users\navin\Downloads\california_housing_train.csv")

print(df)


       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  media

In [ ]:
# 2
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
# 3
df.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

#### Data summery

In [ ]:
# 1
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
# 2
df['total_bedrooms'].unique()

array([1283., 1901.,  174., ..., 1637., 1308.,  936.])

#### Data Transformation

In [ ]:

# 1
df['total_bedrooms_per_total_rooms'] = df['total_bedrooms'] / df['total_rooms']
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  \
0      1015.0       472.0         1.4936             66900.0   
1      1129.0       463.0         1.8200             80100.0   
2       333.0       117.0         1.6509             85700.0   
3       515.0       226.0         3.1917             73400.0   
4       624.0       262.0         1.9250             65500.0   

   total_bedrooms_per_total_rooms  
0                        0.228617  
1                        0.248497  
2                        0.241667  
3                        0.224517  
4                        0.224209

In [ ]:
# 2
df['total_bedrooms_per_total_rooms'].describe()

count    17000.000000
mean         0.212760
std          0.057823
min          0.100000
25%          0.175058
50%          0.202943
75%          0.239867
max          1.000000
Name: total_bedrooms_per_total_rooms, dtype: float64

#### Data filtaring

In [135]:
# 1
df2 = df[df['median_income'] > 5]
print(df2)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  media

In [ ]:
# 2
df3 = df[['total_rooms', 'median_house_value']]
df4 = df3[df3['total_rooms'] > 10000]
df5 = df4[df4['median_house_value'] < 150000]
print(df5)

       total_rooms  median_house_value
133        10377.0             66800.0
191        12557.0             78500.0
198        11836.0            134500.0
201        11115.0             74400.0
229        10105.0             90900.0
...            ...                 ...
12654      12139.0            132500.0
12772      32627.0            118800.0
13388      10869.0             81300.0
13707      11768.0            142900.0
15436      13714.0            100100.0

[67 rows x 2 columns]


#### export modified data

In [ ]:
# modified data frame
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  \
0      1015.0       472.0         1.4936             66900.0   
1      1129.0       463.0         1.8200             80100.0   
2       333.0       117.0         1.6509             85700.0   
3       515.0       226.0         3.1917             73400.0   
4       624.0       262.0         1.9250             65500.0   

   total_bedrooms_per_total_rooms  
0                        0.228617  
1                        0.248497  
2                        0.241667  
3                        0.224517  
4                        0.224209

In [ ]:
# 1
df.to_csv('modified_data_frame.csv')

# Part 2: Numerical Analysis with NumPy

#### Array Creation and Indexing

In [ ]:
# 1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(a)
b = np.array(range(1, 21))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# 2
print(b[1:21:2])

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# 3
c =np.random.randint(10,101, size=(5, 4))
print(c)

[[56 57 37 11]
 [78 60 48 97]
 [70 38 37 14]
 [42 35 95 88]
 [51 63 98 39]]


In [ ]:
# 4
print(c[0:3, 0:2])

[[56 57]
 [78 60]
 [70 38]]


#### Array Manipulation

In [ ]:
# 1
d = b.reshape(4, 5)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# 2
e = d.flatten()
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# 3 
m1 = c[0:3, 0:2]
m2 = np.random.randint(1,95, size=(2, 3))

print(np.dot(m1, m2))

[[4083 4159 7863]
 [4698 4416 9420]
 [3408 2838 7202]]


#### Boolean and Fancy Indexing

In [73]:
# 1
g = np.random.randint(0, 101, size=(1, 50))
print(g)

[[ 6 95 41 18 10 99 70 49 91 76 54  6 78 25 80 28 58 52 73 29 92 13 79 16
  63 12  6 81 67 73 62 15 14  8  9 17 50 23 96 80 31 46 26  1 87 51 83 98
  55 73]]


In [75]:
# 2
boolian_index = g > 50
g[boolian_index]


array([95, 99, 70, 91, 76, 54, 78, 80, 58, 52, 73, 92, 79, 63, 81, 67, 73,
       62, 96, 80, 87, 51, 83, 98, 55, 73], dtype=int32)

In [ ]:
# 3
arr = np.random.rand(2, 2)
arr[0][1]


np.float64(0.9465628200566231)

#### Statistical Operations

##### 1

In [88]:
print(c)

[[56 57 37 11]
 [78 60 48 97]
 [70 38 37 14]
 [42 35 95 88]
 [51 63 98 39]]


In [90]:
cmean = c.mean(axis=0)
print(cmean)


[59.4 50.6 63.  49.8]


In [91]:
c.max(axis=0)

array([78, 63, 98, 97], dtype=int32)

In [92]:
c.sum(axis=0)

array([297, 253, 315, 249])

##### 2

In [94]:
cmean = c.mean(axis=0)
mask = c > cmean
filtererd_c = np.where(mask, c, np.nan)
print(filtererd_c)


[[nan 57. nan nan]
 [78. 60. nan 97.]
 [70. nan nan nan]
 [nan nan 95. 88.]
 [nan 63. 98. nan]]


# Part 3: Problem Solving with Python Basics

####  Loops and Conditional Statements

In [98]:
# 1
print("Fibonacci sequence: ")
a, b = 0, 1
while a <= 100:
    print(a, end=" ")
    a, b = b, a + b

Fibonacci sequence: 
0 1 1 2 3 5 8 13 21 34 55 89 

In [102]:
# 2
for num in range(1, 51):
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz")
    elif num % 3 == 0:
        print("Fizz")
    elif num % 5 == 0:
        print("Buzz")
    else:
        print(num)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


#### Variable-Length Arguments

In [188]:
# 1
def median(num):
    
    sorted_num = sorted(num)
    n = len(sorted_num)
    
    if n % 2 == 1:
        return sorted_num[n // 2]
    else:
        mid1, mid2 = sorted_num[(n // 2) - 1], sorted_num[n // 2]
        return (mid1 + mid2) / 2
    
    if not num:
        print("Error Exist")
num = [8, 9, 7, 2]
m_edian = median(num)
print("Median:", m_edian)

Median: 7.5


In [ ]:
# 2
def avg(*num):
    n = len(num)
    add = sum(num)
    return add / n 
average = avg(4, 6, 7, 9)
print("Average is ", average)
    

Average is  6.5


#### Error handeling

In [198]:
# 1
def avg(*num):
    try:
        n = len(num)
        add = sum(num)
        return add / n
    except ZeroDivisionError:
        print("Error: you have to give one value.")
        return None
 
average = avg()
print("Average is ", average)
    

Error: you have to give one value.
Average is  None


# Part 4: Bonus Challenge 

In [171]:
# 1
kim = np.random.rand(2, 2, 4)
print(kim)

[[[0.53387909 0.29607569 0.28583167 0.98053079]
  [0.62886126 0.56554005 0.95660293 0.37139913]]

 [[0.88255745 0.84192031 0.7440424  0.65136119]
  [0.54023641 0.30844858 0.44078743 0.04293738]]]


In [ ]:
# 2
swap = np.swapaxes(kim, 0, 2)
print(swap)

[[[0.53387909 0.88255745]
  [0.62886126 0.54023641]]

 [[0.29607569 0.84192031]
  [0.56554005 0.30844858]]

 [[0.28583167 0.7440424 ]
  [0.95660293 0.44078743]]

 [[0.98053079 0.65136119]
  [0.37139913 0.04293738]]]


In [ ]:
# 3
kim = np.random.rand(2, 2, 4)
kim.sum(axis=2)


array([[2.37459379, 2.53740252],
       [1.09499383, 0.80665303]])

In [ ]:
# 4
shahrukh_khan = np.random.rand(2,3)
vector = np.array([1, 2, 5])
soln = shahrukh_khan + vector
print(soln)

[[1.75142811 2.23194988 5.04015026]
 [1.43208027 2.4955182  5.24887631]]
